// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/estate-tasks/CalmGrouping.tsx": () => import("../components/mockups/estate-tasks/CalmGrouping.tsx"),
  "./components/mockups/estate-tasks/RefinedDensity.tsx": () => import("../components/mockups/estate-tasks/RefinedDensity.tsx")
};
